# Generated by Django 2.1.15 on 2021-06-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auto_20200322_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proj_info',
            name='git',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proj_info',
            name='total',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
